### ISSUE TITLE
FAILING CI's on Linux Python 3.10.

### ISSUE THREAD

**Issue by skoudoro** [MacPython/dipy-wheels#8]
Hi @matthew-brett,

As you can see [here](https://github.com/MacPython/dipy-wheels/runs/5400957753?check_suite_focus=true#step:10:159) and [here](https://github.com/MacPython/dipy-wheels/runs/5400957803?check_suite_focus=true#step:10:386) I got these 2 errors when I tried to build DIPY wheels on Linux, python3.10.

I have no clue how to fix this issue. Do you have an idea? Thank you in advance for your feedback.

```python
Installed:
  libtool.x86_64 0:1.5.22-7.el5_4         wget.x86_64 0:1.11.4-3.el5_8.2        

Complete!
ls: /opt/python/cp310-cp310/bin: No such file or directory
```

Here, it seems we need to upgrade pip on the docker, but I do not know-how.

```python
ERROR: Exception:
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 390, in run
    installed = install_given_reqs(
  File "/venv/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/venv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 723, in install
    scheme = get_scheme(
  File "/venv/lib/python3.10/site-packages/pip/_internal/locations/__init__.py", line 155, in get_scheme
    new = _sysconfig.get_scheme(
  File "/venv/lib/python3.10/site-packages/pip/_internal/locations/_sysconfig.py", line 131, in get_scheme
    scheme_name = _infer_prefix()
  File "/venv/lib/python3.10/site-packages/pip/_internal/locations/_sysconfig.py", line 45, in _infer_prefix
    return sysconfig.get_preferred_scheme("prefix")  # type: ignore
AttributeError: module 'sysconfig' has no attribute 'get_preferred_scheme'
```

Thank you

**Comment by skoudoro** [comment]
small reference for the 2nd error: https://github.com/pypa/pip/issues/10253

**Comment by skoudoro** [comment]
ok, manylinux1 has been dropped for python3.10, makes sense now. More info on https://github.com/pypa/manylinux/issues/994

closing
